SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `training_usernaming_type` DROP FOREIGN KEY `FK_9D52E925A76ED395` ;
ALTER TABLE `training_usernaming_type` DROP `user_id`;
SET FOREIGN_KEY_CHECKS=1;


SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `oro_user` DROP FOREIGN KEY `IDX_F82840BCBA28E2B9` ;
ALTER TABLE `oro_user` DROP `usernaming_type_id`;
SET FOREIGN_KEY_CHECKS=1;