api:
  entity_aliases:
    Training\Bundle\UserNamingBundle\Entity\UserNamingType:
      alias: usernaming_type
      plural_alias: usernaming_types

  entities:
    Training\Bundle\UserNamingBundle\Entity\UserNamingType:
      documentation_resource: '@TrainingUserNamingBundle/Resources/doc/api/userNamingType.md'
      sorters:
        fields:
          title:
            exclude: false
      filters:
        fields:
          title:
            exclude: false
      fields:
        nameExample:
          data_type: string
          meta_property: true