services:
    Training\Bundle\UserNamingBundle\Command\Debug:
        public: false
        class: Training\Bundle\UserNamingBundle\Command\Debug
        tags:
            - { name: console.command }
