Training\Bundle\UserNamingBundle\Entity\UserNamingType:
  properties:
    title:
#      - NotBlank: ~
      - Length:
          max: 35
    format:
#      - NotBlank: ~
      - Length:
          max: 35